<?php namespace JF;
/**

Copyright 2019 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-c39b0b
Date:    2019-01-08 13:13:23
Version: v2.1.4
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-c39b0b",
    "email": {
        "to": "daniel.mo@qandil.se",
        "cc": "",
        "bcc": "",
        "subject": "QandilJOBS - {f1}",
        "template": "",
        "sendmail_from": "qandiljob@gmail.com",
        "fromName": "QANDILJOBS"
    },
    "admin": {
        "users": "admin:7afeb",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "Hello! We always look forward to go through applications of great people who\u2019d like to work with us at QANDIL. Thank you for applying for a position with us, and here\u2019s a confirmation that we received your application. One of our recruiters will contact you shortly to let you know about the status of your application.\n\n",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "mailgun",
    "smtp": {
        "host": "smtp-mail.outlook.com",
        "user": "@outlook.com",
        "password": "Lacost123",
        "port": "587",
        "security": "tls"
    },
    "mailgun": {
        "domain": "sandbox563006888e58476087d21ca0c9a02b91.mailgun.org",
        "apiKey": "fb69e807400af5b09acd8365cef41ad4-060550c6-a5478ee1",
        "fromEmail": "danial.mohemmed@gmail.com",
        "fromName": "QANDILJOBS"
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                },
                "hidden": true
            },
            "id": "f2",
            "cid": "c2",
            "labelHide": true
        },
        {
            "label": "Upload CV \/ Resume",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "docx,xlsx,pptx,doc,xls,ppt,rtf,pdf,odt,odp,ods,odg,odf,sxw,sxi,sxc,sxd,stw"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f4",
            "cid": "c27"
        },
        {
            "label": "Upload Cover Letter",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "docx,xlsx,pptx,doc,xls,ppt,rtf,pdf,odt,odp,ods,odg,odf,sxw,sxi,sxc,sxd,stw"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f5",
            "cid": "c25"
        },
        {
            "label": "Upload Additional Files",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "docx,xlsx,pptx,doc,xls,ppt,rtf,pdf,odt,odp,ods,odg,odf,sxw,sxi,sxc,sxd,stw"
                },
                "multiple": true
            },
            "id": "f6",
            "cid": "c30"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "no"
    },
    "licenseKey": "",
    "twilio": {
        "toPhone": ""
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class
